import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Profile from "./components/Header/Profile";
import { VStack, Container, Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box m={2}>
            <VStack>
              <Container>
                <Profile />
                {children}
              </Container>
            </VStack>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
